// <auto-generated />
using System;
using AIChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIChat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AIChatDbContext))]
    [Migration("20260729073327_InitialM2DeviceTaskSchema")]
    partial class InitialM2DeviceTaskSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIChat.Domain.Entities.DeviceHost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("MemoryGb")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "HostName")
                        .IsUnique();

                    b.ToTable("device_hosts", (string)null);
                });

            modelBuilder.Entity("AIChat.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeNo")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("AIChat.Domain.Entities.EmployeeClientAccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxDailyUsageMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSessionMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("employee_client_access_policies", (string)null);
                });

            modelBuilder.Entity("AIChat.Domain.Entities.RpaActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AiReplyText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("LoggedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("OcrText")
                        .HasColumnType("text");

                    b.Property<string>("RiskResult")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("RpaClientInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RpaTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("SanitizedScreenshotPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RpaTaskId");

                    b.HasIndex("RpaClientInstanceId", "LoggedAtUtc");

                    b.ToTable("rpa_action_logs", (string)null);
                });

            modelBuilder.Entity("AIChat.Domain.Entities.RpaClientInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientInstanceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CurrentSessionStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastAccessReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LastAccessStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("LastCanContinueRun")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VirtualDeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeChatWorkAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientInstanceKey")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VirtualDeviceId");

                    b.HasIndex("WeChatWorkAccountId");

                    b.ToTable("rpa_client_instances", (string)null);
                });

            modelBuilder.Entity("AIChat.Domain.Entities.RpaTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiReplyText")
                        .HasColumnType("text");

                    b.Property<string>("ConversationKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IncomingMessageText")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RiskResult")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("RpaClientInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WeChatWorkAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WeChatWorkAccountId");

                    b.HasIndex("RpaClientInstanceId", "Status");

                    b.ToTable("rpa_tasks", (string)null);
                });

            modelBuilder.Entity("AIChat.Domain.Entities.VirtualDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceHostId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VmName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("WeChatWorkAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceHostId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WeChatWorkAccountId");

                    b.HasIndex("TenantId", "MachineCode")
                        .IsUnique();

                    b.HasIndex("TenantId", "VmName")
                        .IsUnique();

                    b.ToTable("virtual_devices", (string)null);
                });

            modelBuilder.Entity("AIChat.Domain.Entities.WeChatWorkAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PhoneNumberMasked")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeChatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId", "WeChatId")
                        .IsUnique();

                    b.ToTable("wechat_work_accounts", (string)null);
                });

            modelBuilder.Entity("AIChat.Domain.Entities.EmployeeClientAccessPolicy", b =>
                {
                    b.HasOne("AIChat.Domain.Entities.Employee", "Employee")
                        .WithOne("ClientAccessPolicy")
                        .HasForeignKey("AIChat.Domain.Entities.EmployeeClientAccessPolicy", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.RpaActionLog", b =>
                {
                    b.HasOne("AIChat.Domain.Entities.RpaClientInstance", "RpaClientInstance")
                        .WithMany()
                        .HasForeignKey("RpaClientInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIChat.Domain.Entities.RpaTask", "RpaTask")
                        .WithMany("ActionLogs")
                        .HasForeignKey("RpaTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RpaClientInstance");

                    b.Navigation("RpaTask");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.RpaClientInstance", b =>
                {
                    b.HasOne("AIChat.Domain.Entities.Employee", "Employee")
                        .WithMany("RpaClientInstances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIChat.Domain.Entities.VirtualDevice", "VirtualDevice")
                        .WithMany("RpaClientInstances")
                        .HasForeignKey("VirtualDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIChat.Domain.Entities.WeChatWorkAccount", "WeChatWorkAccount")
                        .WithMany("RpaClientInstances")
                        .HasForeignKey("WeChatWorkAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("VirtualDevice");

                    b.Navigation("WeChatWorkAccount");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.RpaTask", b =>
                {
                    b.HasOne("AIChat.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIChat.Domain.Entities.RpaClientInstance", "RpaClientInstance")
                        .WithMany("RpaTasks")
                        .HasForeignKey("RpaClientInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIChat.Domain.Entities.WeChatWorkAccount", "WeChatWorkAccount")
                        .WithMany("RpaTasks")
                        .HasForeignKey("WeChatWorkAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("RpaClientInstance");

                    b.Navigation("WeChatWorkAccount");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.VirtualDevice", b =>
                {
                    b.HasOne("AIChat.Domain.Entities.DeviceHost", "DeviceHost")
                        .WithMany("VirtualDevices")
                        .HasForeignKey("DeviceHostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIChat.Domain.Entities.Employee", "Employee")
                        .WithMany("VirtualDevices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIChat.Domain.Entities.WeChatWorkAccount", "WeChatWorkAccount")
                        .WithMany()
                        .HasForeignKey("WeChatWorkAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeviceHost");

                    b.Navigation("Employee");

                    b.Navigation("WeChatWorkAccount");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.WeChatWorkAccount", b =>
                {
                    b.HasOne("AIChat.Domain.Entities.Employee", "Employee")
                        .WithMany("WeChatWorkAccounts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.DeviceHost", b =>
                {
                    b.Navigation("VirtualDevices");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.Employee", b =>
                {
                    b.Navigation("ClientAccessPolicy");

                    b.Navigation("RpaClientInstances");

                    b.Navigation("VirtualDevices");

                    b.Navigation("WeChatWorkAccounts");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.RpaClientInstance", b =>
                {
                    b.Navigation("RpaTasks");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.RpaTask", b =>
                {
                    b.Navigation("ActionLogs");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.VirtualDevice", b =>
                {
                    b.Navigation("RpaClientInstances");
                });

            modelBuilder.Entity("AIChat.Domain.Entities.WeChatWorkAccount", b =>
                {
                    b.Navigation("RpaClientInstances");

                    b.Navigation("RpaTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
